{
 "title": "SRS Stat",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "zone", "query": { "query": "srs_build_info" } },
   { "name": "version", "query": { "query": "srs_build_info" } },
   { "name": "server_role", "query": { "query": "srs_build_info" } },
   { "name": "instance", "query": { "query": "srs_build_info" } }
  ]
 },
 "panels": [
  {
   "title": "All Online Servers",
   "type": "piechart",
   "description": "All Online Servers",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(srs_build_info{tag=~\"$server_role\",instance=~\"$instance\",label=~\"$zone\"})by(tag)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Zones",
   "type": "piechart",
   "description": "Server zone distribution",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(srs_build_info{tag=~\"$server_role\",instance=~\"$instance\",label=~\"$zone\"})by(label)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Server Version",
   "type": "piechart",
   "description": "Srs server version",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(srs_build_info{tag=~\"$server_role\",instance=~\"$instance\",label=~\"$zone\"})by(version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Online Streams",
   "type": "stat",
   "description": "All Online Streams",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(srs_streams * on(instance) group_left(tag,label) srs_build_info {tag=~\"$server_role\",instance=~\"$instance\",label=~\"$zone\"})"
    }
   ]
  },
  {
   "title": "All Online Clients",
   "type": "stat",
   "description": "All Online Clients, include publish and play clients",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(srs_clients * on(instance) group_left(tag,label) srs_build_info{tag=~\"$server_role\",instance=~\"$instance\",label=~\"$zone\"})"
    }
   ]
  },
  {
   "title": "Total Clients",
   "type": "stat",
   "description": "All servers total clients",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(srs_clients_total* on(instance) group_left(tag,label) srs_build_info{tag=~\"$server_role\",instance=~\"$instance\",label=~\"$zone\"})"
    }
   ]
  },
  {
   "title": "Clients Success Rate Per",
   "type": "stat",
   "description": "All servers total clients",
   "gridPos": { "h": 6, "w": 3, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(srs_clients_total * on(instance) group_left(tag,label) srs_build_info{tag=~\"$server_role\",instance=~\"$instance\",label=~\"$zone\"}) - sum(srs_clients_errs_total * on(instance) group_left(tag,label) srs_build_info{tag=~\"$server_role\",instance=~\"$instance\",label=~\"$zone\"})) / sum(srs_clients_total * on(instance) group_left(tag,label) srs_build_info{tag=~\"$server_role\",instance=~\"$instance\",label=~\"$zone\"}) * 100"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "SRS Node CPU Percent",
   "type": "timeseries",
   "description": "srs node cpu total percent",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "(sum(1-rate(node_cpu_seconds_total{mode=\"idle\"}[1m]) * on(instance) group_left(nodename) node_uname_info) by (nodename,instance)) * 100"
    }
   ]
  },
  {
   "title": "SRS Process CPU Percent",
   "type": "timeseries",
   "description": "srs process cpu percent",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    { "expr": "srs_cpu_percent" }
   ]
  },
  {
   "title": "SRS Node Memory Per",
   "type": "timeseries",
   "description": "srs node memory percent",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "(1-((node_memory_MemFree_bytes)+(node_memory_Cached_bytes)+(node_memory_Buffers_bytes))/(node_memory_MemTotal_bytes)) * on(instance) group_left(nodename) node_uname_info"
    }
   ]
  },
  {
   "title": "SRS Memory",
   "type": "timeseries",
   "description": "srs memory",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    { "expr": "srs_memory" }
   ]
  },
  {
   "title": "Server Online streams",
   "type": "timeseries",
   "description": "Server Online streams",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "srs_streams * on(instance) group_left(tag,label) srs_build_info{tag=~\"$server_role\",instance=~\"$instance\",label=~\"$zone\"}"
    }
   ]
  },
  {
   "title": "Server Online Clients",
   "type": "timeseries",
   "description": "Display all server online clients, include publish and play clients",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "srs_clients * on(instance) group_left(tag,label) srs_build_info{tag=~\"$server_role\",instance=~\"$instance\",label=~\"$zone\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Send Data Kbps",
   "type": "timeseries",
   "description": "Server Send Data Kbps",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kbps" } },
   "targets": [
    {
     "expr": "rate(srs_send_bytes_total[30s])/1000 * on(instance) group_left(tag,label) srs_build_info{tag=~\"$server_role\",instance=~\"$instance\",label=~\"$zone\"}"
    }
   ]
  },
  {
   "title": "Server Recv Data Kbps",
   "type": "timeseries",
   "description": "Server Recv Data Kbps",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kbps" } },
   "targets": [
    {
     "expr": "rate(srs_receive_bytes_total[30s])*8/1000 * on(instance) group_left(tag,label) srs_build_info{tag=~\"$server_role\",instance=~\"$instance\",label=~\"$zone\"}"
    }
   ]
  },
  {
   "title": "Srs Clients total",
   "type": "timeseries",
   "description": "Srs Clients total",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "srs_clients_total * on(instance) group_left(tag,label) srs_build_info{tag=~\"$server_role\",instance=~\"$instance\",label=~\"$zone\"}"
    }
   ]
  },
  {
   "title": "Srs Clients Err Total",
   "type": "timeseries",
   "description": "Srs Clients Err Total",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "srs_clients_errs_total * on(instance) group_left(tag,label) srs_build_info{tag=~\"$server_role\",instance=~\"$instance\",label=~\"$zone\"}"
    }
   ]
  }
 ]
}